export const styles = {
    app: {
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        position: 'relative',
        overflow: 'hidden',
    },
    bgAnimation: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'linear-gradient(-45deg, #1e3c72, #2a5298, #4facfe, #00f2fe, #43e97b, #38f9d7)',
        backgroundSize: '400% 400%',
        animation: 'gradient 20s ease infinite',
        zIndex: 0,
    },
    header: {
        background: 'rgba(55, 55, 65, 0.85)',
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
        padding: '20px 0',
        position: 'sticky',
        top: 0,
        zIndex: 100,
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
    },
    container: {
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '0 20px',
    },
    headerContent: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
    },
    logoIcon: {
        width: '50px',
        height: '50px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '24px',
        color: 'white',
        boxShadow: '0 8px 20px rgba(79, 172, 254, 0.4)',
        animation: 'float 3s ease-in-out infinite',
    },
    logoText: {
        fontSize: '28px',
        fontWeight: '700',
        color: 'white',
        textShadow: '2px 2px 4px rgba(0,0,0,0.2)',
    },
    userActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
    },
    userInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        background: 'rgba(75, 75, 85, 0.8)',
        padding: '10px 20px',
        borderRadius: '50px',
        backdropFilter: 'blur(10px)',
        border: '1px solid rgba(255, 255, 255, 0.15)',
    },
    userAvatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        fontWeight: '600',
        fontSize: '18px',
    },
    userName: {
        color: 'white',
        fontWeight: '500',
        fontSize: '16px',
    },
    loginButton: {
        padding: '12px 24px',
        background: 'linear-gradient(135deg, #4285f4 0%, #34a853 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '25px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        boxShadow: '0 4px 15px rgba(66, 133, 244, 0.4)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoutButton: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        background: 'rgba(255, 255, 255, 0.2)',
        border: 'none',
        color: 'white',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '14px',
        marginLeft: '8px',
    },
    main: {
        position: 'relative',
        zIndex: 10,
        padding: '40px 0',
    },
    dashboard: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(500px, 1fr))',
        gap: '30px',
        marginBottom: '40px',
    },
    card: {
        background: 'rgba(255, 255, 255, 0.85)',
        backdropFilter: 'blur(20px)',
        borderRadius: '24px',
        padding: '30px',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
        border: '1px solid rgba(255, 255, 255, 0.3)',
        transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    },
    cardHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
        marginBottom: '25px',
    },
    cardIcon: {
        fontSize: '28px',
        color: '#4facfe',
    },
    cardTitle: {
        fontSize: '24px',
        fontWeight: '600',
        color: '#2d3748',
    },
    citySelector: {
        marginBottom: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    cityLabel: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#2d3748',
        display: 'flex',
        alignItems: 'center',
    },
    citySelect: {
        padding: '12px 16px',
        borderRadius: '10px',
        border: '2px solid rgba(79, 172, 254, 0.3)',
        fontSize: '14px',
        fontWeight: '500',
        color: '#2d3748',
        background: 'white',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        outline: 'none',
    },
    mapContainer: {
        position: 'relative',
        borderRadius: '16px',
        overflow: 'hidden',
        boxShadow: 'inset 0 2px 8px rgba(0, 0, 0, 0.1)',
        height: '450px',
        border: '2px solid rgba(79, 172, 254, 0.2)',
    },
    map: {
        width: '100%',
        height: '100%',
    },
    mapHint: {
        marginTop: '15px',
        textAlign: 'center',
        color: '#4a5568',
        fontSize: '14px',
        fontWeight: '500',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    aqiInfo: {
        display: 'flex',
        flexDirection: 'column',
        gap: '25px',
    },
    aqiValueContainer: {
        textAlign: 'center',
        padding: '20px',
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '16px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
    },
    aqiValue: {
        fontSize: '64px',
        fontWeight: '700',
        color: 'white',
        margin: '0 auto 10px',
        width: '140px',
        height: '140px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0 10px 30px rgba(0, 0, 0, 0.3)',
    },
    aqiLabel: {
        color: '#2d3748',
        fontSize: '14px',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    aqiDetails: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '12px',
    },
    detailItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '15px',
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '12px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
        transition: 'all 0.3s ease',
    },
    detailIcon: {
        width: '45px',
        height: '45px',
        borderRadius: '10px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '18px',
        color: 'white',
        flexShrink: 0,
    },
    detailContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '3px',
    },
    detailLabel: {
        fontSize: '11px',
        fontWeight: '600',
        color: '#718096',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    detailValue: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#2d3748',
    },
    detailDesc: {
        fontSize: '10px',
        color: '#a0aec0',
    },
    notificationSettings: {
        padding: '25px',
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '16px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
    },
    notificationHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '15px',
    },
    bellIcon: {
        fontSize: '24px',
        color: '#4facfe',
    },
    notificationTitle: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#2d3748',
    },
    notificationDesc: {
        color: '#4a5568',
        fontSize: '14px',
        marginBottom: '20px',
        lineHeight: '1.6',
    },
    notificationForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    formLabel: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#2d3748',
        display: 'flex',
        alignItems: 'center',
    },
    formSelect: {
        padding: '12px 16px',
        borderRadius: '10px',
        border: '2px solid rgba(79, 172, 254, 0.3)',
        fontSize: '14px',
        fontWeight: '500',
        color: '#2d3748',
        background: 'white',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        outline: 'none',
    },
    btnPrimary: {
        padding: '14px 28px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '12px',
        fontSize: '16px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        boxShadow: '0 8px 20px rgba(79, 172, 254, 0.4)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    aqiLevelsSection: {
        background: 'rgba(255, 255, 255, 0.85)',
        backdropFilter: 'blur(20px)',
        borderRadius: '24px',
        padding: '40px',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
        border: '1px solid rgba(255, 255, 255, 0.3)',
        marginBottom: '40px',
    },
    sectionHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
        marginBottom: '20px',
    },
    sectionIcon: {
        fontSize: '32px',
        color: '#4facfe',
    },
    sectionTitle: {
        fontSize: '28px',
        fontWeight: '700',
        color: '#2d3748',
    },
    sectionDesc: {
        color: '#4a5568',
        fontSize: '16px',
        lineHeight: '1.6',
        marginBottom: '30px',
    },
    aqiLevelsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '20px',
    },
    aqiLevelCard: {
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '16px',
        padding: '25px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
        transition: 'transform 0.3s ease',
    },
    aqiLevelIcon: {
        width: '60px',
        height: '60px',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '28px',
        color: 'white',
        flexShrink: 0,
        boxShadow: '0 4px 15px rgba(0, 0, 0, 0.3)',
    },
    aqiLevelContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    aqiLevelTitle: {
        fontSize: '18px',
        fontWeight: '700',
        color: '#2d3748',
    },
    aqiLevelRange: {
        display: 'inline-block',
        padding: '4px 12px',
        borderRadius: '20px',
        fontSize: '13px',
        fontWeight: '600',
        color: 'white',
        alignSelf: 'flex-start',
    },
    aqiLevelDesc: {
        fontSize: '13px',
        color: '#4a5568',
        lineHeight: '1.4',
    },
    footer: {
        background: 'rgba(50, 50, 60, 0.9)',
        backdropFilter: 'blur(20px)',
        borderTop: '1px solid rgba(255, 255, 255, 0.1)',
        padding: '50px 0 20px',
        position: 'relative',
        zIndex: 10,
    },
    footerContent: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '40px',
        marginBottom: '30px',
    },
    footerSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    footerLogo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    footerLogoIcon: {
        width: '40px',
        height: '40px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        borderRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '20px',
        color: 'white',
    },
    footerLogoText: {
        fontSize: '24px',
        fontWeight: '700',
        color: 'white',
    },
    footerText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: '14px',
        lineHeight: '1.6',
    },
    footerTitle: {
        fontSize: '18px',
        fontWeight: '600',
        color: 'white',
        marginBottom: '10px',
    },
    contactItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    contactIcon: {
        fontSize: '16px',
        color: '#4facfe',
        width: '20px',
    },
    contactText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: '14px',
    },
    socialLinks: {
        display: 'flex',
        gap: '15px',
    },
    socialLink: {
        width: '45px',
        height: '45px',
        borderRadius: '12px',
        background: 'rgba(75, 75, 85, 0.8)',
        backdropFilter: 'blur(10px)',
        border: '1px solid rgba(255, 255, 255, 0.15)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '20px',
        color: 'white',
        textDecoration: 'none',
        transition: 'all 0.3s ease',
    },
    footerBottom: {
        borderTop: '1px solid rgba(255, 255, 255, 0.1)',
        paddingTop: '20px',
        textAlign: 'center',
    },
    copyright: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: '14px',
    },
};
