export const styles = {
    app: {
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        position: 'relative',
        overflow: 'hidden',
    },
    bgAnimation: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'linear-gradient(-45deg, #1e3c72, #2a5298, #4facfe, #00f2fe, #43e97b, #38f9d7)',
        backgroundSize: '400% 400%',
        animation: 'gradient 20s ease infinite',
        zIndex: 0,
    },
    header: {
        background: 'rgba(55, 55, 65, 0.85)',
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
        padding: '20px 0',
        position: 'sticky',
        top: 0,
        zIndex: 100,
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
    },
    container: {
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '0 20px',
    },
    headerContent: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
    },
    logoIcon: {
        width: '50px',
        height: '50px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '24px',
        color: 'white',
        boxShadow: '0 8px 20px rgba(79, 172, 254, 0.4)',
        animation: 'float 3s ease-in-out infinite',
    },
    logoText: {
        fontSize: '28px',
        fontWeight: '700',
        color: 'white',
        textShadow: '2px 2px 4px rgba(0,0,0,0.2)',
    },
    userActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
    },
    userSection: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
    },
    userInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        background: 'rgba(75, 75, 85, 0.8)',
        padding: '10px 20px',
        borderRadius: '50px',
        backdropFilter: 'blur(10px)',
        border: '1px solid rgba(255, 255, 255, 0.15)',
    },
    userAvatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        fontWeight: '600',
        fontSize: '18px',
    },
    userName: {
        color: 'white',
        fontWeight: '500',
        fontSize: '16px',
    },
    userDetails: {
        display: 'flex',
        flexDirection: 'column',
        lineHeight: 1.2,
    },
    userEmail: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: '12px',
    },
    loginButton: {
        padding: '12px 24px',
        background: 'linear-gradient(135deg, #4285f4 0%, #34a853 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '25px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        boxShadow: '0 4px 15px rgba(66, 133, 244, 0.4)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    userMenu: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        background: 'rgba(75, 75, 85, 0.6)',
        padding: '8px 12px',
        borderRadius: '40px',
        border: '1px solid rgba(255, 255, 255, 0.1)',
    },
    menuButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '8px 14px',
        background: 'transparent',
        color: 'white',
        border: 'none',
        borderRadius: '20px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '500',
        transition: 'background 0.3s ease',
    },
    menuButtonActive: {
        background: 'rgba(79, 172, 254, 0.2)',
    },
    profileMenuWrapper: {
        position: 'relative',
    },
    profileDropdown: {
        position: 'absolute',
        top: 'calc(100% + 12px)',
        right: 0,
        width: '280px',
        background: 'rgba(22, 24, 35, 0.95)',
        borderRadius: '18px',
        padding: '18px',
        boxShadow: '0 18px 45px rgba(0, 0, 0, 0.35)',
        border: '1px solid rgba(255, 255, 255, 0.12)',
        backdropFilter: 'blur(16px)',
        zIndex: 250,
        display: 'flex',
        flexDirection: 'column',
        gap: '14px',
        animation: 'fadeIn 0.2s ease',
    },
    profileSummary: {
        display: 'flex',
        alignItems: 'center',
        gap: '14px',
    },
    profileSummaryAvatar: {
        width: '48px',
        height: '48px',
        borderRadius: '16px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        fontWeight: '600',
        fontSize: '18px',
        boxShadow: '0 10px 25px rgba(79, 172, 254, 0.4)',
    },
    profileSummaryDetails: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    profileSummaryName: {
        color: 'white',
        fontWeight: '600',
        fontSize: '16px',
    },
    profileSummaryEmail: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: '12px',
        letterSpacing: '0.3px',
    },
    profileDivider: {
        height: '1px',
        background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.25), transparent)',
        border: 'none',
    },
    profileActions: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    profileActionButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        width: '100%',
        padding: '10px 12px',
        borderRadius: '12px',
        border: 'none',
        background: 'rgba(79, 172, 254, 0.15)',
        color: 'white',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'background 0.3s ease',
    },
    profileActionButtonSecondary: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        width: '100%',
        padding: '10px 12px',
        borderRadius: '12px',
        border: '1px dashed rgba(255, 255, 255, 0.2)',
        background: 'transparent',
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: '13px',
        cursor: 'not-allowed',
    },
    profileFooter: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
    },
    profileStatus: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: '12px',
    },
    profileLogoutButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px 12px',
        borderRadius: '12px',
        border: 'none',
        background: 'rgba(255, 99, 71, 0.2)',
        color: '#ff6b6b',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'background 0.3s ease',
    },
    notificationDot: {
        display: 'inline-block',
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        background: '#48bb78',
        marginLeft: '6px',
        boxShadow: '0 0 6px rgba(72, 187, 120, 0.8)',
    },
    logoutButton: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        background: 'rgba(255, 255, 255, 0.2)',
        border: 'none',
        color: 'white',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '14px',
        marginLeft: '8px',
    },
    loadingIndicator: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: 'rgba(255, 255, 255, 0.9)',
        background: 'rgba(75, 75, 85, 0.6)',
        padding: '10px 18px',
        borderRadius: '30px',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        fontSize: '14px',
        fontWeight: '500',
    },
    main: {
        position: 'relative',
        zIndex: 10,
        padding: '40px 0',
    },
    authError: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '12px 18px',
        marginBottom: '20px',
        borderRadius: '12px',
        background: 'rgba(255, 99, 71, 0.15)',
        border: '1px solid rgba(255, 99, 71, 0.4)',
        color: '#ff6b6b',
        fontWeight: '500',
        backdropFilter: 'blur(6px)',
    },
    dashboard: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(500px, 1fr))',
        gap: '30px',
        marginBottom: '40px',
    },
    card: {
        background: 'rgba(255, 255, 255, 0.85)',
        backdropFilter: 'blur(20px)',
        borderRadius: '24px',
        padding: '30px',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
        border: '1px solid rgba(255, 255, 255, 0.3)',
        transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    },
    cardHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
        marginBottom: '25px',
    },
    cardIcon: {
        fontSize: '28px',
        color: '#4facfe',
    },
    cardTitle: {
        fontSize: '24px',
        fontWeight: '600',
        color: '#2d3748',
    },
    citySelector: {
        marginBottom: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    cityLabel: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#2d3748',
        display: 'flex',
        alignItems: 'center',
    },
    citySelect: {
        padding: '12px 16px',
        borderRadius: '10px',
        border: '2px solid rgba(79, 172, 254, 0.3)',
        fontSize: '14px',
        fontWeight: '500',
        color: '#2d3748',
        background: 'white',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        outline: 'none',
    },
    mapContainer: {
        position: 'relative',
        borderRadius: '16px',
        overflow: 'hidden',
        boxShadow: 'inset 0 2px 8px rgba(0, 0, 0, 0.1)',
        height: '450px',
        border: '2px solid rgba(79, 172, 254, 0.2)',
    },
    map: {
        width: '100%',
        height: '100%',
    },
    mapHint: {
        marginTop: '15px',
        textAlign: 'center',
        color: '#4a5568',
        fontSize: '14px',
        fontWeight: '500',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    aqiInfo: {
        display: 'flex',
        flexDirection: 'column',
        gap: '25px',
    },
    aqiValueContainer: {
        textAlign: 'center',
        padding: '20px',
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '16px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
    },
    aqiValue: {
        fontSize: '64px',
        fontWeight: '700',
        color: 'white',
        margin: '0 auto 10px',
        width: '140px',
        height: '140px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0 10px 30px rgba(0, 0, 0, 0.3)',
    },
    aqiLabel: {
        color: '#2d3748',
        fontSize: '14px',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    aqiDetails: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '12px',
    },
    detailItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '15px',
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '12px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
        transition: 'all 0.3s ease',
    },
    detailIcon: {
        width: '45px',
        height: '45px',
        borderRadius: '10px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '18px',
        color: 'white',
        flexShrink: 0,
    },
    detailContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '3px',
    },
    detailLabel: {
        fontSize: '11px',
        fontWeight: '600',
        color: '#718096',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    detailValue: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#2d3748',
    },
    detailDesc: {
        fontSize: '10px',
        color: '#a0aec0',
    },
    notificationSettings: {
        padding: '25px',
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '16px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
    },
    notificationLocked: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '10px',
        padding: '20px',
        background: 'rgba(75, 75, 85, 0.15)',
        borderRadius: '16px',
        border: '1px dashed rgba(79, 172, 254, 0.4)',
        color: 'rgba(45, 55, 72, 0.9)',
        fontWeight: '500',
        backdropFilter: 'blur(6px)',
    },
    notificationHelper: {
        marginTop: '16px',
        padding: '10px 12px',
        borderRadius: '12px',
        background: 'rgba(72, 187, 120, 0.1)',
        border: '1px solid rgba(72, 187, 120, 0.3)',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
    },
    notificationHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '15px',
    },
    bellIcon: {
        fontSize: '24px',
        color: '#4facfe',
    },
    notificationTitle: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#2d3748',
    },
    notificationDesc: {
        color: '#4a5568',
        fontSize: '14px',
        marginBottom: '20px',
        lineHeight: '1.6',
    },
    notificationForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    formLabel: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#2d3748',
        display: 'flex',
        alignItems: 'center',
    },
    formSelect: {
        padding: '12px 16px',
        borderRadius: '10px',
        border: '2px solid rgba(79, 172, 254, 0.3)',
        fontSize: '14px',
        fontWeight: '500',
        color: '#2d3748',
        background: 'white',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        outline: 'none',
    },
    btnPrimary: {
        padding: '14px 28px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '12px',
        fontSize: '16px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        boxShadow: '0 8px 20px rgba(79, 172, 254, 0.4)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0, 0, 0, 0.65)',
        backdropFilter: 'blur(8px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 200,
        padding: '20px',
    },
    modalContent: {
        width: '100%',
        maxWidth: '520px',
        background: 'white',
        borderRadius: '20px',
        boxShadow: '0 30px 80px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255, 255, 255, 0.8)',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        animation: 'modalSlideIn 0.3s ease-out',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        padding: '24px 28px 16px',
        borderBottom: '1px solid rgba(226, 232, 240, 0.6)',
    },
    modalTitle: {
        fontSize: '22px',
        fontWeight: '700',
        color: '#1a202c',
        marginBottom: '6px',
    },
    modalSubtitle: {
        color: '#4a5568',
        fontSize: '14px',
        lineHeight: 1.5,
    },
    modalCloseButton: {
        width: '32px',
        height: '32px',
        borderRadius: '10px',
        border: 'none',
        background: 'rgba(148, 163, 184, 0.25)',
        color: '#1a202c',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'all 0.3s ease',
        fontSize: '16px',
    },
    modalBody: {
        padding: '20px 28px 16px',
        display: 'flex',
        flexDirection: 'column',
        gap: '22px',
    },
    modalSectionTitle: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#2d3748',
        marginBottom: '6px',
    },
    modalSectionText: {
        fontSize: '14px',
        color: '#4a5568',
        lineHeight: 1.6,
        marginBottom: '12px',
    },
    modalActionsRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        flexWrap: 'wrap',
    },
    modalPrimaryButton: {
        padding: '12px 20px',
        borderRadius: '12px',
        border: 'none',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        color: 'white',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        transition: 'transform 0.2s ease, box-shadow 0.3s ease',
        boxShadow: '0 12px 25px rgba(79, 172, 254, 0.35)',
    },
    modalSecondaryButton: {
        padding: '12px 20px',
        borderRadius: '12px',
        border: '1px solid rgba(148, 163, 184, 0.5)',
        background: 'transparent',
        color: '#2d3748',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        transition: 'background 0.3s ease',
    },
    modalFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '12px',
        padding: '20px 28px 24px',
        borderTop: '1px solid rgba(226, 232, 240, 0.6)',
    },
    modalSelect: {
        width: '100%',
        padding: '12px 16px',
        borderRadius: '12px',
        border: '2px solid rgba(148, 163, 184, 0.4)',
        background: 'white',
        fontSize: '14px',
        fontWeight: '500',
        color: '#2d3748',
        outline: 'none',
        transition: 'border 0.2s ease',
        cursor: 'pointer',
    },
    locationPreview: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        padding: '10px 14px',
        borderRadius: '12px',
        background: 'rgba(72, 187, 120, 0.15)',
        color: '#22543d',
        fontWeight: '600',
    },
    statusMessage: {
        marginTop: '14px',
        padding: '12px 14px',
        borderRadius: '12px',
        border: '1px solid transparent',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        lineHeight: 1.4,
    },
    modalInfoBox: {
        display: 'flex',
        alignItems: 'center',
        padding: '12px 14px',
        borderRadius: '12px',
        background: 'rgba(66, 153, 225, 0.12)',
        color: '#2b6cb0',
        border: '1px solid rgba(66, 153, 225, 0.2)',
        fontSize: '14px',
    },
    aqiLevelsSection: {
        background: 'rgba(255, 255, 255, 0.85)',
        backdropFilter: 'blur(20px)',
        borderRadius: '24px',
        padding: '40px',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
        border: '1px solid rgba(255, 255, 255, 0.3)',
        marginBottom: '40px',
    },
    sectionHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
        marginBottom: '20px',
    },
    sectionIcon: {
        fontSize: '32px',
        color: '#4facfe',
    },
    sectionTitle: {
        fontSize: '28px',
        fontWeight: '700',
        color: '#2d3748',
    },
    sectionDesc: {
        color: '#4a5568',
        fontSize: '16px',
        lineHeight: '1.6',
        marginBottom: '30px',
    },
    aqiLevelsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '20px',
    },
    aqiLevelCard: {
        background: 'rgba(255, 255, 255, 0.6)',
        backdropFilter: 'blur(10px)',
        borderRadius: '16px',
        padding: '25px',
        border: '1px solid rgba(79, 172, 254, 0.2)',
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
        transition: 'transform 0.3s ease',
    },
    aqiLevelIcon: {
        width: '60px',
        height: '60px',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '28px',
        color: 'white',
        flexShrink: 0,
        boxShadow: '0 4px 15px rgba(0, 0, 0, 0.3)',
    },
    aqiLevelContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    aqiLevelTitle: {
        fontSize: '18px',
        fontWeight: '700',
        color: '#2d3748',
    },
    aqiLevelRange: {
        display: 'inline-block',
        padding: '4px 12px',
        borderRadius: '20px',
        fontSize: '13px',
        fontWeight: '600',
        color: 'white',
        alignSelf: 'flex-start',
    },
    aqiLevelDesc: {
        fontSize: '13px',
        color: '#4a5568',
        lineHeight: '1.4',
    },
    footer: {
        background: 'rgba(50, 50, 60, 0.9)',
        backdropFilter: 'blur(20px)',
        borderTop: '1px solid rgba(255, 255, 255, 0.1)',
        padding: '50px 0 20px',
        position: 'relative',
        zIndex: 10,
    },
    footerContent: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '40px',
        marginBottom: '30px',
    },
    footerSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    footerLogo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    footerLogoIcon: {
        width: '40px',
        height: '40px',
        background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        borderRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '20px',
        color: 'white',
    },
    footerLogoText: {
        fontSize: '24px',
        fontWeight: '700',
        color: 'white',
    },
    footerText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: '14px',
        lineHeight: '1.6',
    },
    footerTitle: {
        fontSize: '18px',
        fontWeight: '600',
        color: 'white',
        marginBottom: '10px',
    },
    contactItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    contactIcon: {
        fontSize: '16px',
        color: '#4facfe',
        width: '20px',
    },
    contactText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: '14px',
    },
    socialLinks: {
        display: 'flex',
        gap: '15px',
    },
    socialLink: {
        width: '45px',
        height: '45px',
        borderRadius: '12px',
        background: 'rgba(75, 75, 85, 0.8)',
        backdropFilter: 'blur(10px)',
        border: '1px solid rgba(255, 255, 255, 0.15)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '20px',
        color: 'white',
        textDecoration: 'none',
        transition: 'all 0.3s ease',
    },
    footerBottom: {
        borderTop: '1px solid rgba(255, 255, 255, 0.1)',
        paddingTop: '20px',
        textAlign: 'center',
    },
    copyright: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: '14px',
    },
};
